# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'inventory' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for inventory
      pod 'Firebase/Core'
      pod 'Firebase/Auth', '~> 5.15.0'
      pod 'Firebase/Firestore', '~> 5.15.0'
      pod 'Firebase/Storage', '~> 5.15.0'
  target 'inventory-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

    pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  end

  target 'inventoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
